version: "3.1"
services:
 influxdb:
  image: influxdb:1.8.3
  container_name: test-influxdb
  ports:
   - 8086:8086
  volumes:
   - ./test-data:/var/lib/influxdb
   - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
  command: -config /etc/influxdb/influxdb.conf
