version: "3"
services:
 mongo-setup:
  container_name: mongo-setup
  image: mongo:4.4.0
  volumes:
   - ./script:/script
  entrypoint: ["sh", "/script/setup.sh"]
  depends_on:
    - mongo-1
    - mongo-2
    - mongo-3
 mongo-1:
  container_name: mongo-1
  image: mongo:4.4.0
  ports:
   - 30000:27017
  volumes:
   - ./test-data1:/data/db
  command: mongod --replSet my-mongo
 mongo-2:
  container_name: mongo-2
  image: mongo:4.4.0
  ports:
   - 30001:27017
  volumes:
   - ./test-data2:/data/db
  command: mongod --replSet my-mongo
 mongo-3:
  container_name: mongo-3
  image: mongo:4.4.0
  ports:
   - 30002:27017
  volumes:
   - ./test-data3:/data/db
  command: mongod --replSet my-mongo