version: '3'
services:
 server1:
  image: mariadb:10.1.38
  container_name: test-server1
  ports: 
   - 3307:3306
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./test-data1:/var/lib/mysql
   - ./server1/master.sql:/docker-entrypoint-initdb.d/master.sql
   - ./server1/server.cnf:/etc/mysql/conf.d/server.cnf
  environment: 
   - MYSQL_ROOT_PASSWORD=root
  restart: always
 server2:
  image: mariadb:10.1.38
  container_name: test-server2
  depends-on:
   - test-server1
  ports: 
   - 3308:3306
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./test-data2:/var/lib/mysql
   - ./server2/slave.sql:/docker-entrypoint-initdb.d/slave.sql
   - ./server2/server.cnf:/etc/mysql/conf.d/server.cnf
  environment: 
   - MYSQL_ROOT_PASSWORD=root
  restart: always
 server3:
  image: mariadb:10.1.38
  container_name: test-server3
  depends-on:
   - test-server1
  ports: 
   - 3309:3306
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./test-data3:/var/lib/mysql
   - ./server3/slave.sql:/docker-entrypoint-initdb.d/slave.sql
   - ./server3/server.cnf:/etc/mysql/conf.d/server.cnf
  environment: 
   - MYSQL_ROOT_PASSWORD=root
  restart: always